version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node
        environment:  
          BUNDLER_VERSION: 2.0.1              
          PGHOST: localhost
          PGUSER: fainda_api
          RAILS_ENV: test
      - image: postgres:10.7-alpine

        environment:
          POSTGRES_USER: fainda_api
          POSTGRES_DB: fainda_api_test
          POSTGRES_PASSWORD: ""
        run:
          name: install dependencies
          command: |
            sudo gem update --system
            sudo gem install rspec
            sudo gem uninstall bundler
            sudo rm /usr/local/bin/bundle
            sudo gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
          
    steps:
      - checkout
        # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: fainda_api-{{ checksum "Gemfile.lock" }}
        # Bundle install dependencies
      - run: bundle install --path vendor/bundle
        # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: fainda_api-{{ checksum "Gemfile.lock" }}
        paths: 
          - vendor/bundle
      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      # Setup the environment
      - run: cp .sample.env .env
      # Setup the database
      - run: bundle exec rake db:setup
      



